#!/bin/bash

# Perform system checks and configure them if not as expected

GRUB_CONSOLE=1
GRUB_TIMEOUT=1
NTP_CONFIG=1
FIREWALL_DISABLED=1
APPARMOR_DISABLED=1
IPv6_DISABLED=1
DHCP_HOSTNAME_DISABLED=1
CLEAN_ZYPP_LOG=1
REPOS_CONFIGURED=1
SYS_UPDATED=1
